[project]
name = "ds-diabetes-challenge"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "imbalanced-learn>=0.14.2",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.50",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
